package app.brykaobd.obd

/**
 * Public SAE J2012-style generic (P0xxx) DTC descriptions in Polish.
 * Manufacturer-specific P1/P3 and network U-codes stay as fallback until curated separately.
 */
internal object DtcCatalogPl {
    val map: Map<String, String> = mapOf(
        // Fuel / mixture
        "P0100" to "Przepływomierz powietrza (MAF) — usterka obwodu",
        "P0101" to "Przepływomierz powietrza (MAF) — zakres / wydajność",
        "P0102" to "Przepływomierz powietrza (MAF) — sygnał za niski",
        "P0103" to "Przepływomierz powietrza (MAF) — sygnał za wysoki",
        "P0104" to "Przepływomierz powietrza (MAF) — sygnał przerywany",
        "P0105" to "Ciśnienie absolutne kolektora (MAP) — usterka obwodu",
        "P0106" to "MAP — zakres / wydajność",
        "P0107" to "MAP — sygnał za niski",
        "P0108" to "MAP — sygnał za wysoki",
        "P0109" to "MAP — sygnał przerywany",
        "P0110" to "Czujnik temperatury powietrza wlotowego (IAT) — usterka obwodu",
        "P0111" to "IAT — zakres / wydajność",
        "P0112" to "IAT — sygnał za niski",
        "P0113" to "IAT — sygnał za wysoki",
        "P0114" to "IAT — sygnał przerywany",
        "P0115" to "Czujnik temperatury płynu chłodzącego (ECT) — usterka obwodu",
        "P0116" to "ECT — zakres / wydajność",
        "P0117" to "ECT — sygnał za niski",
        "P0118" to "ECT — sygnał za wysoki",
        "P0119" to "ECT — sygnał przerywany",
        "P0120" to "Czujnik położenia przepustnicy (TPS) A — usterka obwodu",
        "P0121" to "TPS A — zakres / wydajność",
        "P0122" to "TPS A — sygnał za niski",
        "P0123" to "TPS A — sygnał za wysoki",
        "P0124" to "TPS A — sygnał przerywany",
        "P0125" to "Temperatura płynu — zbyt niska do zamkniętej pętli",
        "P0126" to "Temperatura płynu — niewystarczająca do stabilnej pracy",
        "P0127" to "Temperatura powietrza wlotowego za wysoka",
        "P0128" to "Termostat chłodzenia — temperatura poniżej regulacji",
        "P0130" to "Sonda lambda bank 1 czujnik 1 — usterka obwodu",
        "P0131" to "Sonda lambda B1S1 — napięcie za niskie",
        "P0132" to "Sonda lambda B1S1 — napięcie za wysokie",
        "P0133" to "Sonda lambda B1S1 — wolna odpowiedź",
        "P0134" to "Sonda lambda B1S1 — brak aktywności",
        "P0135" to "Sonda lambda B1S1 — grzałka",
        "P0136" to "Sonda lambda bank 1 czujnik 2 — usterka obwodu",
        "P0137" to "Sonda lambda B1S2 — napięcie za niskie",
        "P0138" to "Sonda lambda B1S2 — napięcie za wysokie",
        "P0139" to "Sonda lambda B1S2 — wolna odpowiedź",
        "P0140" to "Sonda lambda B1S2 — brak aktywności",
        "P0141" to "Sonda lambda B1S2 — grzałka",
        "P0150" to "Sonda lambda bank 2 czujnik 1 — usterka obwodu",
        "P0151" to "Sonda lambda B2S1 — napięcie za niskie",
        "P0152" to "Sonda lambda B2S1 — napięcie za wysokie",
        "P0153" to "Sonda lambda B2S1 — wolna odpowiedź",
        "P0154" to "Sonda lambda B2S1 — brak aktywności",
        "P0155" to "Sonda lambda B2S1 — grzałka",
        "P0156" to "Sonda lambda bank 2 czujnik 2 — usterka obwodu",
        "P0157" to "Sonda lambda B2S2 — napięcie za niskie",
        "P0158" to "Sonda lambda B2S2 — napięcie za wysokie",
        "P0160" to "Sonda lambda B2S2 — brak aktywności",
        "P0161" to "Sonda lambda B2S2 — grzałka",
        "P0170" to "Korekcja mieszanki (bank 1) — usterka",
        "P0171" to "Układ paliwowy zbyt ubogi (bank 1)",
        "P0172" to "Układ paliwowy zbyt bogaty (bank 1)",
        "P0173" to "Korekcja mieszanki (bank 2) — usterka",
        "P0174" to "Układ paliwowy zbyt ubogi (bank 2)",
        "P0175" to "Układ paliwowy zbyt bogaty (bank 2)",
        "P0180" to "Czujnik temperatury paliwa A — usterka obwodu",
        "P0181" to "Czujnik temperatury paliwa A — zakres / wydajność",
        "P0182" to "Czujnik temperatury paliwa A — sygnał za niski",
        "P0183" to "Czujnik temperatury paliwa A — sygnał za wysoki",
        "P0190" to "Czujnik ciśnienia paliwa w szynie — usterka obwodu",
        "P0191" to "Ciśnienie paliwa w szynie — zakres / wydajność",
        "P0192" to "Ciśnienie paliwa w szynie — sygnał za niski",
        "P0193" to "Ciśnienie paliwa w szynie — sygnał za wysoki",

        // Injectors / misfire
        "P0200" to "Wtryskiwacz — usterka obwodu",
        "P0201" to "Wtryskiwacz cylinder 1 — usterka obwodu",
        "P0202" to "Wtryskiwacz cylinder 2 — usterka obwodu",
        "P0203" to "Wtryskiwacz cylinder 3 — usterka obwodu",
        "P0204" to "Wtryskiwacz cylinder 4 — usterka obwodu",
        "P0205" to "Wtryskiwacz cylinder 5 — usterka obwodu",
        "P0206" to "Wtryskiwacz cylinder 6 — usterka obwodu",
        "P0207" to "Wtryskiwacz cylinder 7 — usterka obwodu",
        "P0208" to "Wtryskiwacz cylinder 8 — usterka obwodu",
        "P0217" to "Przegrzanie silnika",
        "P0218" to "Przegrzanie skrzyni biegów",
        "P0219" to "Przekroczenie maksymalnych obrotów silnika",
        "P0220" to "TPS / przełącznik B — usterka obwodu",
        "P0221" to "TPS B — zakres / wydajność",
        "P0222" to "TPS B — sygnał za niski",
        "P0223" to "TPS B — sygnał za wysoki",
        "P0230" to "Pompa paliwa — obwód pierwotny",
        "P0231" to "Pompa paliwa — obwód wtórny niski",
        "P0232" to "Pompa paliwa — obwód wtórny wysoki",
        "P0234" to "Turbodoładowanie — zbyt wysokie ciśnienie",
        "P0235" to "Czujnik ciśnienia doładowania A — usterka obwodu",
        "P0236" to "Czujnik ciśnienia doładowania A — zakres / wydajność",
        "P0237" to "Czujnik ciśnienia doładowania A — sygnał za niski",
        "P0238" to "Czujnik ciśnienia doładowania A — sygnał za wysoki",
        "P0243" to "Elektrozawór wastegate A",
        "P0245" to "Elektrozawór wastegate A — niski",
        "P0246" to "Elektrozawór wastegate A — wysoki",
        "P0261" to "Wtryskiwacz cylinder 1 — obwód niski",
        "P0262" to "Wtryskiwacz cylinder 1 — obwód wysoki",
        "P0264" to "Wtryskiwacz cylinder 2 — obwód niski",
        "P0265" to "Wtryskiwacz cylinder 2 — obwód wysoki",
        "P0267" to "Wtryskiwacz cylinder 3 — obwód niski",
        "P0268" to "Wtryskiwacz cylinder 3 — obwód wysoki",
        "P0270" to "Wtryskiwacz cylinder 4 — obwód niski",
        "P0271" to "Wtryskiwacz cylinder 4 — obwód wysoki",
        "P0299" to "Turbodoładowanie — zbyt niskie ciśnienie (underboost)",
        "P0300" to "Wypadanie zapłonu (losowe / wiele cylindrów)",
        "P0301" to "Wypadanie zapłonu — cylinder 1",
        "P0302" to "Wypadanie zapłonu — cylinder 2",
        "P0303" to "Wypadanie zapłonu — cylinder 3",
        "P0304" to "Wypadanie zapłonu — cylinder 4",
        "P0305" to "Wypadanie zapłonu — cylinder 5",
        "P0306" to "Wypadanie zapłonu — cylinder 6",
        "P0307" to "Wypadanie zapłonu — cylinder 7",
        "P0308" to "Wypadanie zapłonu — cylinder 8",

        // Knock / crank / cam
        "P0320" to "Czujnik prędkości obrotowej silnika — usterka obwodu",
        "P0321" to "Czujnik prędkości obrotowej — zakres / wydajność",
        "P0322" to "Czujnik prędkości obrotowej — brak sygnału",
        "P0325" to "Czujnik spalania stukowego 1 (bank 1) — usterka obwodu",
        "P0326" to "Czujnik spalania stukowego 1 — zakres / wydajność",
        "P0327" to "Czujnik spalania stukowego 1 — sygnał za niski",
        "P0328" to "Czujnik spalania stukowego 1 — sygnał za wysoki",
        "P0330" to "Czujnik spalania stukowego 2 (bank 2) — usterka obwodu",
        "P0335" to "Czujnik położenia wału korbowego A — usterka obwodu",
        "P0336" to "Czujnik wału korbowego A — zakres / wydajność",
        "P0337" to "Czujnik wału korbowego A — sygnał za niski",
        "P0338" to "Czujnik wału korbowego A — sygnał za wysoki",
        "P0339" to "Czujnik wału korbowego A — sygnał przerywany",
        "P0340" to "Czujnik położenia wałka rozrządu A (bank 1) — usterka obwodu",
        "P0341" to "Czujnik wałka rozrządu A — zakres / wydajność",
        "P0342" to "Czujnik wałka rozrządu A — sygnał za niski",
        "P0343" to "Czujnik wałka rozrządu A — sygnał za wysoki",
        "P0344" to "Czujnik wałka rozrządu A — sygnał przerywany",
        "P0350" to "Cewka zapłonowa — usterka obwodu pierwotnego/wtórnego",
        "P0351" to "Cewka zapłonowa A — cylinder 1",
        "P0352" to "Cewka zapłonowa B — cylinder 2",
        "P0353" to "Cewka zapłonowa C — cylinder 3",
        "P0354" to "Cewka zapłonowa D — cylinder 4",
        "P0355" to "Cewka zapłonowa E — cylinder 5",
        "P0356" to "Cewka zapłonowa F — cylinder 6",

        // EGR / AIR / EVAP / catalyst
        "P0400" to "Układ EGR — przepływ",
        "P0401" to "EGR — niewystarczający przepływ",
        "P0402" to "EGR — nadmierny przepływ",
        "P0403" to "EGR — obwód zaworu / sterowanie",
        "P0404" to "EGR — zakres / wydajność",
        "P0405" to "Czujnik pozycji EGR A — sygnał za niski",
        "P0406" to "Czujnik pozycji EGR A — sygnał za wysoki",
        "P0407" to "Czujnik pozycji EGR B — sygnał za niski",
        "P0408" to "Czujnik pozycji EGR B — sygnał za wysoki",
        "P0409" to "Czujnik pozycji EGR A — usterka obwodu",
        "P0410" to "Układ wtórnego powietrza (AIR)",
        "P0411" to "AIR — nieprawidłowy przepływ",
        "P0420" to "Sprawność katalizatora poniżej progu (bank 1)",
        "P0421" to "Podgrzewanie katalizatora poniżej progu (bank 1)",
        "P0430" to "Sprawność katalizatora poniżej progu (bank 2)",
        "P0431" to "Podgrzewanie katalizatora poniżej progu (bank 2)",
        "P0440" to "Układ EVAP — usterka ogólna",
        "P0441" to "EVAP — nieprawidłowy przepływ oczyszczania",
        "P0442" to "EVAP — mały wyciek",
        "P0443" to "EVAP — zawór oczyszczania — usterka obwodu",
        "P0444" to "EVAP — zawór oczyszczania — obwód otwarty",
        "P0445" to "EVAP — zawór oczyszczania — zwarcie",
        "P0446" to "EVAP — sterowanie odpowietrzaniem — usterka obwodu",
        "P0447" to "EVAP — odpowietrzanie — obwód otwarty",
        "P0448" to "EVAP — odpowietrzanie — zwarcie",
        "P0449" to "EVAP — zawór odpowietrzający — usterka obwodu",
        "P0450" to "Czujnik ciśnienia EVAP — usterka obwodu",
        "P0451" to "Czujnik ciśnienia EVAP — zakres / wydajność",
        "P0452" to "Czujnik ciśnienia EVAP — sygnał za niski",
        "P0453" to "Czujnik ciśnienia EVAP — sygnał za wysoki",
        "P0455" to "EVAP — duży wyciek",
        "P0456" to "EVAP — bardzo mały wyciek",
        "P0457" to "EVAP — wyciek (korek wlewu)",
        "P0460" to "Czujnik poziomu paliwa — usterka obwodu",
        "P0461" to "Czujnik poziomu paliwa — zakres / wydajność",
        "P0462" to "Czujnik poziomu paliwa — sygnał za niski",
        "P0463" to "Czujnik poziomu paliwa — sygnał za wysoki",
        "P0480" to "Wentylator chłodnicy 1 — sterowanie",
        "P0481" to "Wentylator chłodnicy 2 — sterowanie",

        // Vehicle speed / idle / PCM
        "P0500" to "Czujnik prędkości pojazdu A",
        "P0501" to "Czujnik prędkości pojazdu A — zakres / wydajność",
        "P0502" to "Czujnik prędkości pojazdu A — sygnał za niski",
        "P0503" to "Czujnik prędkości pojazdu A — sygnał przerywany / wysoki",
        "P0505" to "Regulacja biegu jałowego (IAC)",
        "P0506" to "IAC — obroty jałowe za niskie",
        "P0507" to "IAC — obroty jałowe za wysokie",
        "P0510" to "Przełącznik zamkniętej przepustnicy",
        "P0520" to "Czujnik ciśnienia oleju silnikowego — usterka obwodu",
        "P0521" to "Ciśnienie oleju — zakres / wydajność",
        "P0522" to "Ciśnienie oleju — sygnał za niski",
        "P0523" to "Ciśnienie oleju — sygnał za wysoki",
        "P0530" to "Czujnik ciśnienia czynnika A/C — usterka obwodu",
        "P0560" to "Napięcie układu — usterka",
        "P0561" to "Napięcie układu — niestabilne",
        "P0562" to "Napięcie układu — za niskie",
        "P0563" to "Napięcie układu — za wysokie",
        "P0600" to "Łącze komunikacyjne szeregowe",
        "P0601" to "Moduł sterujący — błąd sumy kontrolnej pamięci",
        "P0602" to "Moduł sterujący — błąd programowania",
        "P0603" to "Moduł sterujący — błąd pamięci KAM",
        "P0604" to "Moduł sterujący — błąd pamięci RAM",
        "P0605" to "Moduł sterujący — błąd pamięci ROM",
        "P0606" to "Moduł sterujący PCM / ECM — usterka procesora",
        "P0607" to "Moduł sterujący — wydajność",
        "P0627" to "Pompa paliwa A — sterowanie obwodu otwarte",
        "P0628" to "Pompa paliwa A — sterowanie obwodu niskie",
        "P0629" to "Pompa paliwa A — sterowanie obwodu wysokie",
        "P0638" to "Siłownik przepustnicy — zakres / wydajność (bank 1)",
        "P0641" to "Napięcie odniesienia czujnika A — obwód otwarty",
        "P0651" to "Napięcie odniesienia czujnika B — obwód otwarty",

        // Transmission (generic)
        "P0700" to "Usterka skrzyni biegów (żądanie MIL / TCM)",
        "P0705" to "Czujnik zakresu skrzyni (PRNDL) — usterka obwodu",
        "P0706" to "Czujnik zakresu skrzyni — zakres / wydajność",
        "P0710" to "Czujnik temperatury oleju skrzyni — usterka obwodu",
        "P0711" to "Temperatura oleju skrzyni — zakres / wydajność",
        "P0715" to "Czujnik prędkości wału wejściowego — usterka obwodu",
        "P0720" to "Czujnik prędkości wału wyjściowego — usterka obwodu",
        "P0730" to "Nieprawidłowe przełożenie",
        "P0740" to "Sprzęgło konwertera momentu — usterka obwodu",
        "P0741" to "Sprzęgło konwertera — zablokowane / nie działa",
        "P0750" to "Elektrozawór zmiany biegów A",
        "P0753" to "Elektrozawór zmiany biegów A — elektryczny",
        "P0755" to "Elektrozawór zmiany biegów B",
        "P0758" to "Elektrozawór zmiany biegów B — elektryczny",

        // Diesel / DPF / NOx (common generic)
        "P2002" to "Filtr cząstek stałych (DPF) — sprawność poniżej progu (bank 1)",
        "P2003" to "Filtr cząstek stałych (DPF) — sprawność poniżej progu (bank 2)",
        "P2031" to "Czujnik temperatury spalin (bank 1 czujnik 2) — usterka obwodu",
        "P2032" to "Czujnik temperatury spalin B1S2 — sygnał za niski",
        "P2033" to "Czujnik temperatury spalin B1S2 — sygnał za wysoki",
        "P2080" to "Czujnik temperatury spalin B1S1 — zakres / wydajność",
        "P2084" to "Czujnik temperatury spalin B1S2 — zakres / wydajność",
        "P2263" to "Układ doładowania — wydajność",
        "P242F" to "Filtr cząstek stałych — zablokowanie / nadmierne nagromadzenie sadzy",
        "P244A" to "DPF — zbyt niska różnica ciśnień",
        "P244B" to "DPF — zbyt wysoka różnica ciśnień",
        "P2452" to "Czujnik różnicy ciśnień DPF A — usterka obwodu",
        "P2453" to "Czujnik różnicy ciśnień DPF A — zakres / wydajność",
        "P2454" to "Czujnik różnicy ciśnień DPF A — sygnał za niski",
        "P2455" to "Czujnik różnicy ciśnień DPF A — sygnał za wysoki",
        "P2458" to "Czas regeneracji DPF",
        "P2459" to "Częstotliwość regeneracji DPF",
        "P2463" to "Nagromadzenie sadzy w DPF — ograniczenie",

        // Network (common)
        "U0100" to "Utrata komunikacji z ECM/PCM A",
        "U0101" to "Utrata komunikacji z TCM",
        "U0121" to "Utrata komunikacji z modulem ABS",
        "U0140" to "Utrata komunikacji z modulem nadwozia (BCM)",
        "U0155" to "Utrata komunikacji z modulem wskaźników (IPC)",
        "U0401" to "Nieprawidłowe dane z ECM/PCM A",
    )
}
